export const RIGHT_ONLY = "RIGHT_ONLY";
export const REQUIRED_RIGHT = "REQUIRED_RIGHT";
export const FEATURE_INSTALLED = "FEATURE_INSTALLED";
export const FEATURE_ACTIVATED = "FEATURE_ACTIVATED";
export const FEATURE_READY = "FEATURE_READY";
